print('my name is jayanti')
print('my fathers name is Duhshasan panda')
print('my mother name is Gita rani panda')
print('my younger brother name is Deepak panda')
print('my granda mother name is Hemalata panda')